In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings; warnings.simplefilter('ignore')

In [2]:
data = pd.read_csv("E:\\AUT\\Machine Learning\\PML_HW3\\DataSet\\1\\Parkinson.csv")

In [3]:
data.shape

(195, 24)

In [4]:
data.head()

name  MDVP:Fo(Hz)  MDVP:Fhi(Hz)  MDVP:Flo(Hz)  MDVP:Jitter(%)  \
0  phon_R01_S01_1      119.992       157.302        74.997         0.00784   
1  phon_R01_S01_2      122.400       148.650       113.819         0.00968   
2  phon_R01_S01_3      116.682       131.111       111.555         0.01050   
3  phon_R01_S01_4      116.676       137.871       111.366         0.00997   
4  phon_R01_S01_5      116.014       141.781       110.655         0.01284   

   MDVP:Jitter(Abs)  MDVP:RAP  MDVP:PPQ  Jitter:DDP  MDVP:Shimmer  ...  \
0           0.00007   0.00370   0.00554     0.01109       0.04374  ...   
1           0.00008   0.00465   0.00696     0.01394       0.06134  ...   
2           0.00009   0.00544   0.00781     0.01633       0.05233  ...   
3           0.00009   0.00502   0.00698     0.01505       0.05492  ...   
4           0.00011   0.00655   0.00908     0.01966       0.06425  ...   

   Shimmer:DDA      NHR     HNR  status      RPDE       DFA   spread1  \
0      0.06545  0.02211  21.033       1  0.414783  0.815285 -4.813031   
1      0.09403  0.01929  19.085       1  0.458359  0.819521 -4.075192   
2      0.08270  0.01309  20.651       1  0.429895  0.825288 -4.443179   
3      0.08771  0.01353  20.644       1  0.434969  0.819235 -4.117501   
4      0.10470  0.01767  19.649       1  0.417356  0.823484 -3.747787   

    spread2        D2       PPE  
0  0.266482  2.301442  0.284654  
1  0.335590  2.486855  0.368674  
2  0.311173  2.342259  0.332634  
3  0.334147  2.405554  0.368975  
4  0.234513  2.332180  0.410335  

[5 rows x 24 columns]

In [5]:
from sklearn.preprocessing import StandardScaler
X = data.loc[:,(data.columns != 'name') & (data.columns != "status")]
y = data['status']
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

In [7]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='linear', random_state=1)
svclassifier.fit(X_train, y_train)

SVC(kernel='linear', random_state=1)

In [8]:
y_pred = svclassifier.predict(X_test)

In [9]:
from sklearn.metrics import classification_report, confusion_matrix
print("The confusion matrix and classification report for 'linear' SVM:")
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

The confusion matrix and classification report for 'linear' SVM:
[[ 5  3]
 [ 3 28]]
              precision    recall  f1-score   support

           0       0.62      0.62      0.62         8
           1       0.90      0.90      0.90        31

    accuracy                           0.85        39
   macro avg       0.76      0.76      0.76        39
weighted avg       0.85      0.85      0.85        39



In [10]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='poly', degree=5, C=2, gamma='auto', random_state=1)
svclassifier.fit(X_train, y_train)

SVC(C=2, degree=5, gamma='auto', kernel='poly', random_state=1)

In [11]:
y_pred = svclassifier.predict(X_test)

In [12]:
from sklearn.metrics import classification_report, confusion_matrix
print("The confusion matrix and classification report for 'polynomial' SVM: degree=5, C=2")
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

The confusion matrix and classification report for 'polynomial' SVM: degree=5, C=2
[[ 4  4]
 [ 0 31]]
              precision    recall  f1-score   support

           0       1.00      0.50      0.67         8
           1       0.89      1.00      0.94        31

    accuracy                           0.90        39
   macro avg       0.94      0.75      0.80        39
weighted avg       0.91      0.90      0.88        39



In [13]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='rbf', random_state=1, gamma=0.1)
svclassifier.fit(X_train, y_train)

SVC(gamma=0.1, random_state=1)

In [14]:
y_pred = svclassifier.predict(X_test)

In [15]:
from sklearn.metrics import classification_report, confusion_matrix
print("The confusion matrix and classification report for 'rbf' SVM, gamma=0.1")
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

The confusion matrix and classification report for 'rbf' SVM, gamma=0.1
[[ 5  3]
 [ 0 31]]
              precision    recall  f1-score   support

           0       1.00      0.62      0.77         8
           1       0.91      1.00      0.95        31

    accuracy                           0.92        39
   macro avg       0.96      0.81      0.86        39
weighted avg       0.93      0.92      0.92        39



In [16]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='sigmoid',gamma='auto', C=0.5)
svclassifier.fit(X_train, y_train)

SVC(C=0.5, gamma='auto', kernel='sigmoid')

In [17]:
y_pred = svclassifier.predict(X_test)

In [18]:
from sklearn.metrics import classification_report, confusion_matrix
print("The confusion matrix and classification report for 'sigmoid' SVM, C=0.5:")
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

The confusion matrix and classification report for 'sigmoid' SVM, C=0.5:
[[ 4  4]
 [ 2 29]]
              precision    recall  f1-score   support

           0       0.67      0.50      0.57         8
           1       0.88      0.94      0.91        31

    accuracy                           0.85        39
   macro avg       0.77      0.72      0.74        39
weighted avg       0.84      0.85      0.84        39



In [19]:
from sklearn.model_selection import GridSearchCV

In [20]:
#param_grid = {'C': [0.1,1, 10, 100], 'gamma':[1,0.1,0.01,0.001,0.005],'degree':[1,2,3,5,8],kernel': ['rbf', 'poly', 'sigmoid']}

In [21]:
from sklearn.model_selection import GridSearchCV
param_grid = { 'gamma':[0.4,0.5,0.01,0.001,0.05,0.1], 'kernel': ['rbf']}
grid = GridSearchCV(SVC(),param_grid, refit = True)
grid.fit(X_train,y_train)
print(grid.best_estimator_)

SVC(gamma=0.1)


In [22]:
grid_predictions = grid.predict(X_test)
print(confusion_matrix(y_test,grid_predictions))
print(classification_report(y_test,grid_predictions))

[[ 5  3]
 [ 0 31]]
              precision    recall  f1-score   support

           0       1.00      0.62      0.77         8
           1       0.91      1.00      0.95        31

    accuracy                           0.92        39
   macro avg       0.96      0.81      0.86        39
weighted avg       0.93      0.92      0.92        39



In [23]:
from sklearn.model_selection import GridSearchCV
param_grid = { 'C': [1,2,3,4,5,6], 'degree':[2,3,4,5,6,7,8],'kernel': ['poly']}
grid = GridSearchCV(SVC(),param_grid, refit = True)
grid.fit(X_train,y_train)
print(grid.best_params_)

{'C': 4, 'degree': 3, 'kernel': 'poly'}


In [24]:
grid_predictions = grid.predict(X_test)
print(confusion_matrix(y_test,grid_predictions))
print(classification_report(y_test,grid_predictions))

[[ 4  4]
 [ 0 31]]
              precision    recall  f1-score   support

           0       1.00      0.50      0.67         8
           1       0.89      1.00      0.94        31

    accuracy                           0.90        39
   macro avg       0.94      0.75      0.80        39
weighted avg       0.91      0.90      0.88        39



In [25]:
param_grid = { 'C': [1,2,3,0.1,0.01,0.001,0.005], 'kernel': ['sigmoid']}
grid = GridSearchCV(SVC(),param_grid, refit = True)
grid.fit(X_train,y_train)
print(grid.best_estimator_)

SVC(C=2, kernel='sigmoid')


In [26]:
grid_predictions = grid.predict(X_test)
print(confusion_matrix(y_test,grid_predictions))
print(classification_report(y_test,grid_predictions))

[[ 4  4]
 [ 2 29]]
              precision    recall  f1-score   support

           0       0.67      0.50      0.57         8
           1       0.88      0.94      0.91        31

    accuracy                           0.85        39
   macro avg       0.77      0.72      0.74        39
weighted avg       0.84      0.85      0.84        39

